#!/bin/bash

#PBS -N JavierAcevedo26
#PBS -l nodes=1:intel:ppn=8
# PBS -l walltime=:5:00
#PBS -M ja.acevedo12@uniandes.edu.co
#PBS -m ae
#PBS -j oe
#PBS -o out26.log

# cd $PBS_O_WORKDIR

pwd
cd ja.acevedo12/JavierAcevedo_Ejercicio26

module load anaconda/python3
./partirArchivos.sh
#cp sample.pdf ..
# mkdir images
# mkdir datFiles
cp time.txt 8core.txt

# mv -f $TMPDIR/CollisionalDarkMatterSimulation/images/ ./images
# mv -f $TMPDIR/CollisionalDarkMatterSimulation/datFiles/ ./datFiles





