#!/bin/bash

#PBS -N JavierAcevedo25
#PBS -l nodes=1:ppn=8:intel
#PBS -l walltime=:500:00
#PBS -l mem=28gb
#PBS -M ja.acevedo12@uniandes.edu.co
#PBS -m ae
#PBS -j oe
#PBS -o out25.log

# cd $PBS_O_WORKDIR

pwd
cd ja.acevedo12/JavierAcevedo_Ejercicio25

module load anaconda/python3
make
cp sample.pdf ..
# mkdir images
# mkdir datFiles


# mv -f $TMPDIR/CollisionalDarkMatterSimulation/images/ ./images
# mv -f $TMPDIR/CollisionalDarkMatterSimulation/datFiles/ ./datFiles





